### ISSUE TITLE
dataloader example

### ISSUE THREAD

**Issue by rese1f** [OpenDriveLab/DriveLM#10]
Hi, I am new in this area, can u provide a example .ipynb for drivelm dataloader? I dont know how to build the map from frame name in .json like "4a0798f849ca477ab18009c3a20b7df2" to filename like "n008-2018-05-21-11-06-59-0400__CAM_FRONT__1526915244512465".

Thank you

**Comment by rese1f** [comment]
solved

**Comment by jorgemn9** [comment]
How did you solve it? Thanks in advance
