### ISSUE TITLE
Questions about submission

### ISSUE THREAD

**Issue by zjtco-yr** [OpenDriveLab/DriveLM#100]
Hi

My team name on Google Forms is USTC-IAT-United. In the submission.json file I submitted, the value of the "team" field is "USTC-IAT-United", but I encountered the following error:
[ERROR] Evaluation failed. 'ddb615d9bb22484cabc6545b632a1025_888dd9afb9bc43e2bfbc5e92835a2b26_9' The team name in your submission is [USTC-IAT-United].

**Comment by jeremyxu1998** [comment]
Hi there, your question has been answered in FAQ here: https://github.com/OpenDriveLab/DriveLM/tree/main/challenge#i-encountered-keyerror-b789de07180846cc972118ee6d1fb027_b0e6fd5561454b2789c853e5350557a8_0-in-my-submission-comment-what-should-i-do, please see if you can reproduce it locally first

**Comment by Camellia-hz** [comment]
@zjtco-yr Hello, how did you resolve this?
