### ISSUE TITLE
Inquiry About BLIP-2 Fine-Tuning Code

### ISSUE THREAD

**Issue by fengfengyue** [OpenDriveLab/DriveLM#101]
Hello, I noticed that in your paper, you mention fine-tuning the BLIP-2 model using the DriveLM-nuScenes dataset. However, the provided code only includes the LLaMA-Adapter model. Could you please share the code for fine-tuning the BLIP-2 model as described?
Thank you.

**Comment by ChonghaoSima** [comment]
Thanks for your interest. We are working on the code clean up and will release them in the future, please stay tuned. On the other hand, we suggest you using the LLaMA-Adapter one because it supports multi-view input, which is a gread advancement compared to blip-2.
