### ISSUE TITLE
question about technical report

### ISSUE THREAD

**Issue by yabuke** [OpenDriveLab/DriveLM#102]
Hello, I would like to ask if there is a template for the technical report?

**Comment by ChonghaoSima** [comment]
We recommend cvpr template.

Best
Chonghao Sima
________________________________
From: yabuke ***@***.***>
Sent: Sunday, June 2, 2024 10:08:14 AM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] question about technical report (Issue #102)

---- External Email: Use caution with attachments, links, or sharing data ----


Hello, I would like to ask if there is a template for the technical report?
