### ISSUE TITLE
Behavior Representation

### ISSUE THREAD

**Issue by SaraMo14** [OpenDriveLab/DriveLM#103]
Hi,

could you explain how you have discretized x and y to obtain a behavior representation as:
Bsp ∈ {fast2, fast1, moderate, slow1, slow2},
Bst ∈ {left2, left1, straight, right1, right2}?

Thanks!

**Comment by ChonghaoSima** [comment]
It's an empirical setting and we have tried bin size with 3 5 7 9. It turns out that 5 reaches the balance between the efficiency and effectiveness.
