### ISSUE TITLE
leaderboard reopen?

### ISSUE THREAD

**Issue by JiaweiZhao-git** [OpenDriveLab/DriveLM#105]
Great benchmark! When will the leaderboard reopen for new submission?

**Comment by ChonghaoSima** [comment]
We will notify you when it’s re-open. Estimation will be in a few months. We need to refine some metrics and setting.

Best
Chonghao Sima
________________________________
From: Jiawei Zhao ***@***.***>
Sent: Thursday, June 27, 2024 12:19:27 PM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] leaderboard reopen? (Issue #105)

---- External Email: Use caution with attachments, links, or sharing data ----


Great benchmark! When will the leaderboard reopen for new submission?

**Comment by ChonghaoSima** [comment]
Leaderboard reopened: https://huggingface.co/spaces/AGC2024/driving-with-language-official
