### ISSUE TITLE
Question About v1_1_train_nus.json

### ISSUE THREAD

**Issue by FleverX** [OpenDriveLab/DriveLM#106]
Great Benchmark! 
Can you explain how to generate the v1_1_train_nus.json file?
 If I want to use my own data to run the model, how should I generate the JSON file in the corresponding format? Can I just provide images directly?
Thanks for your time!

**Comment by ChonghaoSima** [comment]
Not sure what do you mean by "generate the v1_1_train_nus.json" but here is the [link](https://drive.google.com/file/d/1CvTPwChKvfnvrZ1Wr0ZNVqtibkkNeGgt/view) that you can download the data. This data is produced by a data labelling pipeline, which you could see in paper section 2 and supp section B&C.

If you want to use your own data, first you should prepare your data in a VQA format, including image and question and answer. Then you need to write a data format converter to get the JSON file in the same format.

**Comment by FleverX** [comment]
> Not sure what do you mean by "generate the v1_1_train_nus.json" but here is the [link](https://drive.google.com/file/d/1CvTPwChKvfnvrZ1Wr0ZNVqtibkkNeGgt/view) that you can download the data. This data is produced by a data labelling pipeline, which you could see in paper section 2 and supp section B&C.
> 
> If you want to use your own data, first you should prepare your data in a VQA format, including image and question and answer. Then you need to write a data format converter to get the JSON file in the same format.

Thanks for your reply! 
For the further question, If I use the Drive-LM data provided by you during the fine-tuning stage and then test the performance with my own data during the inference stage, do I still need to process my data in the way you mentioned above? （in a VQA formate including image and question and answer......）

**Comment by ChonghaoSima** [comment]
It totally depends on your model architecture. If your model accepts video / image frames as input, then yes. Note that the drivelm-data are provided in a single-frame format, while you can add more history frames to train the model as well.

**Comment by FleverX** [comment]
got it， thanks for your time!
