### ISSUE TITLE
About the annotation

### ISSUE THREAD

**Issue by chaoqunwangcs** [OpenDriveLab/DriveLM#107]
Hi， it's great work for AD's development with LLM.
I'd like to annotate similar annotations in my own data, and I want to align it with DriveLM-nuScenes, Could you please tell me how to select the key objects from the keyframe? With a rule between the distance with ego or object size? location? interaction with ego's further status? or human manually select?

**Comment by ChonghaoSima** [comment]
Step 1:
  1. Do not select the first two frames or the last two frames.
  2. Choose a minimum of 4 frames and a maximum of 8 frames per scene.
  3. Do not select three or more consecutive frames.
  4. Criteria for selecting key frames:
    i. Presence of vehicles/traffic signals/pedestrians/other noteworthy obstacles.
    ii.  Rich scene information.
    iii. Frames where the own vehicle may undergo a change of action in the future.

Step 2:
  1. Select a key frame count between 3 and 6 for each frame.
  2. Objects chosen should be as close to the own vehicle as possible (i.e., likely to be referenced by the driving vehicle).
  3. Choose a diverse range of object types for annotation, try to avoid selecting densely grouped individuals as key frames (e.g., selecting one person from a group clustered together), and avoid duplication of overlapping boxes representing the same object.
  4. You can manually draw boxes for objects not present in the predefined boxes but could affect the driving of the own vehicle (e.g., traffic lights, road signs, poles, ground markings, etc.). Ensure that the 'obj_id' attribute for manually drawn boxes is set to -1.

Step 3:
  1. When answering questions, consider providing comprehensive answers. If both options are valid, choose different answers whenever possible.
  2. Provide responses for all empty fields.
  3. For global questions, verify if they have been annotated.
  4. For questions with free-form answers/comments, ensure at least one entry is filled out in each of the two sections.

Among the listed requirements, 1.1, 1.2, 1.3, 2.1, 3.2, and 3.3 will be pre-checked by the platform, reducing the workload for reviewers. These sections only need to be understood by annotation personnel. The rest of the content requires understanding by both annotation and review teams.
