### ISSUE TITLE
Traffic Light Status

### ISSUE THREAD

**Issue by SaraMo14** [OpenDriveLab/DriveLM#108]
How do you retrieve information about traffic light status from nuScenes?
How do you determine which traffic signal the ego vehicle should pay attention to?

In DriveLM-nuScenes I see QA of the type: "What is the traffic signal that the ego vehicle should pay attention to?"  "A": "Green light."

**Comment by ChonghaoSima** [comment]
1. Traffic light status comes from [OpenLaneV2](https://github.com/OpenDriveLab/OpenLane-V2)
2. The human annotator determine which traffic signal the ego vehicle should pay attention to. The rule is that it should be associated to the lane in which the ego vehicle is on and the traffic light will give information on the change of the driving behavior.
