### ISSUE TITLE
The purpose of using key objects

### ISSUE THREAD

**Issue by exiawsh** [OpenDriveLab/DriveLM#11]
Hi, thanks for your great work! What's the purpose of the defination of key objects. It seems that the key objects is both in the questions and answers part. Do you expect the definition of Key objects to appear in pre prompt or do you need post-processing to replace it with a standardized format?

**Comment by ChonghaoSima** [comment]
The definition of key objects is used in the prediction and planning stages, where those questions will only consider the key objects. 

"Do you expect the definition of Key objects to appear in pre prompt or do you need post-processing to replace it with a standardized format?" I am not fully understanding this, could you elaborate a bit?

**Comment by exiawsh** [comment]
@ChonghaoSima Can it be leaked to the model? Or the model still needs to make its own predictions.

**Comment by ChonghaoSima** [comment]
It should be predicted by the models in the perception stages. Then in the prediction and planning stage, we assume the model already “know” the key objects. That’s what we said in the paper, that those QAs are in a logical order.

Best
Chonghao Sima
________________________________

**Comment by exiawsh** [comment]
Thank you!
