### ISSUE TITLE
submission question

### ISSUE THREAD

**Issue by Camellia-hz** [OpenDriveLab/DriveLM#110]
Hi
My team name on Google Forms is hao0110. In the submission.json file I submitted, the value of the "team" field is "hao0110", but I encountered the following error:
[ERROR] Evaluation failed. No available key left! The team name in your submission is [hao0110].
Why is that, please?
Best
@ChonghaoSima

**Comment by Camellia-hz** [comment]
I've noticed.：**always use your team name submitted on Google registration form for the team field, NOT the anonymous team name to be shown on the leaderboard.** 
What does that mean?

**Comment by ChonghaoSima** [comment]
> I've noticed.：**always use your team name submitted on Google registration form for the team field, NOT the anonymous team name to be shown on the leaderboard.** What does that mean?

It means you should use the same team name across all the submit portal, including google form and huggingface test server. 

It seems like an openai key error. We may look into detail soon.

**Comment by Camellia-hz** [comment]
Thanks for the reply, I made sure I used the same name on my submission.json as on huggingface "hao0110"

**Comment by Camellia-hz** [comment]
Dear author, when will this problem be fixed?

**Comment by Camellia-hz** [comment]
Dear author, when will this problem be fixed?
@ChonghaoSima

**Comment by ChonghaoSima** [comment]
We are working on it, estimated time will be next week

Best
Chonghao Sima
________________________________

**Comment by ChonghaoSima** [comment]
> Thank you very much! I will close this issue.

fixed

**Comment by THU-Kingmin** [comment]
[ERROR] Evaluation failed. No available key left! The team name in your submission is [].
