### ISSUE TITLE
[ERROR] Evaluation failed. No available key left! The team name in your submission is [hao0110].

### ISSUE THREAD

**Issue by THU-Kingmin** [OpenDriveLab/DriveLM#111]
[ERROR] Evaluation failed. No available key left! The team name in your submission is [].

**Comment by ChonghaoSima** [comment]
Will keep you post when fix

**Comment by THU-Kingmin** [comment]
Thank you very much for your reply, when is it expected to be resolved please?

**Comment by THU-Kingmin** [comment]
@ChonghaoSima

**Comment by scl-01** [comment]
+1@ChonghaoSima

**Comment by ChonghaoSima** [comment]
We are actively searching for the resources needed. Please be patient.

Best
Chonghao Sima
________________________________

**Comment by THU-Kingmin** [comment]
Thank you very much for your help!

**Comment by ChonghaoSima** [comment]
Seems like test server is down. We are actively reaching out hf team for support and the estimated time of fix may vary.

**Comment by THU-Kingmin** [comment]
thx!

**Comment by ChonghaoSima** [comment]
> Is it possible that GPT4's API is in arrears?

It's due to other reasons about account type as well as the test server bandwith.

**Comment by ChonghaoSima** [comment]
Test server back online.
