### ISSUE TITLE
Inquiry about the length of motion prediction.

### ISSUE THREAD

**Issue by TorresYangX** [OpenDriveLab/DriveLM#113]
Hello, authors, thanks for your work. 

Based on Appendix D.3 of your paper, the Metrics you used calculated the average error between the motion prediction for the next 1 to 3 seconds and the ground truth. However, I noticed that many key frames are less than 3 seconds away from the end of their corresponding scenes. Could you clarify what the ground truth is for these key frames when making motion predictions?

Thanks!

**Comment by ChonghaoSima** [comment]
This is aligned to how UniAD handles these cases. In a short, we only evaluate frames with 3s trajectories and those unqualified frames won't be evaluated for this metrics.

**Comment by TorresYangX** [comment]
I would like to follow up with another question:
How did you calculate the ADE? For example, for the 2-second prediction, did you calculate the ADE directly using the offset, or did you first reconstruct the 2-second trajectory based on the 1-second and 2-second offset predictions and then calculate the ADE?

**Comment by ChonghaoSima** [comment]
Not sure what do you mean by "first reconstruct the 2-second trajectory based on the 1-second and 2-second offset predictions and then calculate the ADE", our ADE calculation can refer to https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/datasets/eval_utils/metric_utils.py#L6
