### ISSUE TITLE
[ERROR] Evaluation failed. No available key left!

### ISSUE THREAD

**Issue by TamamoNa** [OpenDriveLab/DriveLM#116]
Following #115,  we have tried to submit several times, but it doesn't work for us and this error persists. it's still caused by HF server?

**Comment by ChonghaoSima** [comment]
Please re-submit and see if the error still exists.

**Comment by NaNaoiSong** [comment]
![image](https://github.com/user-attachments/assets/a2bb4da4-1d4f-47c3-926d-7e2026c194a8)

I have tried again, but it still failed.

**Comment by TamamoNa** [comment]
![image](https://github.com/user-attachments/assets/86d2d583-1523-4be1-90ce-ab8872779a7f)

I have tried again, but it still failed.
