### ISSUE TITLE
The server for testing encountered an error?

### ISSUE THREAD

**Issue by QixingJiang** [OpenDriveLab/DriveLM#117]
I have tried to submit new submissions 3 times around 2024-09-11 03:14:25 , and all of them FAILED without returning any error messages. I have excluded error with my submission content or format, and I suspect that there is an error with the testing server, which can be reproduced. Could you please identify the cause and fix it? Thank you.
@ChonghaoSima

**Comment by chaoqunwangcs** [comment]
+1, I met the same question, and the submission format remains the same as the previous submissions, but got failed without any logs.

**Comment by ChonghaoSima** [comment]
hf team is fixing this due to a safety patch updated yesterday
![image](https://github.com/user-attachments/assets/580c7f2a-9408-493f-99a0-f09dbefae6cc)

**Comment by QixingJiang** [comment]
The issue has been resolved, and the previously FAILED submissions now have new results. Therefore, this issue can be closed.
