### ISSUE TITLE
Baseline Results Dataset Split

### ISSUE THREAD

**Issue by ayesha-ishaq** [OpenDriveLab/DriveLM#124]
Hi, 

I want to ask regarding the results reported in your paper, which dataset split are they reported on? Secondly, I see you have shared the [zero-shot results](https://github.com/OpenDriveLab/DriveLM/tree/main/challenge#results) on llama adapter v2 baseline on your test set. Do you have fine tuned results on this model on your test set and will you release those?

Many thanks!

**Comment by ChonghaoSima** [comment]
Will provide a finetuned internvl-2.0 model in the future.
