### ISSUE TITLE
Fail Submission to The Evaluation Server

### ISSUE THREAD

**Issue by farrosalferro** [OpenDriveLab/DriveLM#125]
Hello, good job on the project. I encountered this error

`[ERROR] Evaluation failed. No available key left! The team name in your submission is [MyTeamName]`

when submitting the test file to the evaluation server. I used the baseline model (llama adapter) and did the inference on the v1_1_val_nus_1_only.json dataset. I have run the prepare_submission.py file with accordance to the guidance and filled the google forms with the same name as the submission.

I know the competition is already closed, but I want to know if my future model can perform competitively compared to previous approaches. Thank you!

**Comment by fcjian** [comment]
I have the same problem: [ERROR] Evaluation failed. No available key left! The team name in your submission is [**].

**Comment by fcjian** [comment]
@ChonghaoSima How can we solve this problem? Alternatively, since the competition has ended now, can you open-source the VQA of the test set for evaluation?

**Comment by ChonghaoSima** [comment]
@fcjian @farrosalferro Hi all, the server is back online. But now given limited resource, the evaluation time may take up to 2-3 hrs per submission. We will try to optimize it soon.

**Comment by fcjian** [comment]
@ChonghaoSima Thank you. There seems to be another problem: [ERROR] Evaluation failed. 'choices'.

**Comment by ChonghaoSima** [comment]
> @ChonghaoSima Thank you. There seems to be another problem: [ERROR] Evaluation failed. 'choices'.

you could try to update your submission file and re-submit to hf server again. We faced similar issue before.

**Comment by ayesha-ishaq** [comment]
> > @ChonghaoSima Thank you. There seems to be another problem: [ERROR] Evaluation failed. 'choices'.
> 
> you could try to update your submission file and re-submit to hf server again. We faced similar issue before.

Hi, I tried this, yet I got the same error twice.

**Comment by fcjian** [comment]
@ChonghaoSima Thank you, now we can proceed with the testing. However, I have noticed that the evaluation scores of the ChatGPT are relatively low at present. For example, for the same submitted file, the previous ChatGPT score was 65, while the current ChatGPT score is 56.
