### ISSUE TITLE
Failed submission

### ISSUE THREAD

**Issue by NaNaoiSong** [OpenDriveLab/DriveLM#127]
Thanks for the good job and the long-term maintenance of the server.
I encounter some submission error these two days and comments show:
`[ERROR] Evaluation failed. No available key left!`  and `[ERROR] Evaluation failed. 'choices' `
It seems like the test server is down?

**Comment by ChonghaoSima** [comment]
Fixed. The keys are expired and we replaced them. Please try to re-submit again.

**Comment by Camellia-hz** [comment]
@ChonghaoSima Hello, I am experiencing the same problem~ What can I do to solve it?

**Comment by NaNaoiSong** [comment]
Thanks, it works now.
