### ISSUE TITLE
Repeatedly getting [ERROR] Evaluation failed. 'choices' on test server.

### ISSUE THREAD

**Issue by ayesha-ishaq** [OpenDriveLab/DriveLM#129]
Hi,

I repeatedly get the error [ERROR] Evaluation failed. 'choices' on the test server, and many times, all 3 of my submissions get wasted due to this. Can this please be addressed? 

Many thanks

**Comment by ChonghaoSima** [comment]
Some of the openai key have no quota. We are replacing them soon.

**Comment by ChonghaoSima** [comment]
Fixed. Please try to submit again.
