### ISSUE TITLE
Rule-based generation

### ISSUE THREAD

**Issue by nassimbel** [OpenDriveLab/DriveLM#13]
Hello,
Thank you for this work, it is very interesting and helpful.
I have read carefully the paper you put on arxiv, and there is not detailed explanation on the type of rules you used for the dataset building (Particularly NuScenes ). Can you please provide me with some details or implementations?
Best,
Nassim.

**Comment by ChonghaoSima** [comment]
Hello,

Now we don't have such a plan to release the dataset building detail now, as we may use the test data for the challenge (CVPR 2024). But at some point we may release it as a data_building.py
