### ISSUE TITLE
CARLA version question

### ISSUE THREAD

**Issue by Sheep-YangLi** [OpenDriveLab/DriveLM#130]
Hello, thank you for the open-source of this great work. I would like to ask if the Carla version used is 9.14 or higher? When I evaluated route_validation.xml, it said that thereis no Town13 in the map. I am not sure whether this is due to the Carla version problem or something else?

**Comment by RenzKa** [comment]
Hi, thanks for your interest in the work. 
Yes Town 13 is indeed not part of the 9.14 release. To include Town 13 you can either use the official Carla Leaderboard package (https://leaderboard.carla.org/get_started/) which is based on 9.14 but with Town 13 included or directly use the 9.15 version.
