### ISSUE TITLE
Inquiry about Full or Extended Dataset Release Timeline

### ISSUE THREAD

**Issue by ZiruiSongBest** [OpenDriveLab/DriveLM#2]
Hi! 
 I would like to extend my gratitude to your team for publishing this valuable demo dataset. May I inquire if there are plans to release a complete or more extensive version of the dataset in the near future? Do you have any plans to release this dataset before the upcoming CVPR conference? It would be extremely helpful for preparing related research work. 
 
 best

**Comment by yellinshadows** [comment]
Hi, just to clarify, does it mean that this dataset only contains the demo at the moment? I noticed a table in readme saying that most sets have been released (screenshot is as follow). So I get confused.

<img width="862" alt="截屏2023-09-15 22 23 41" src="https://github.com/OpenDriveLab/DriveLM/assets/113589817/f805a293-1359-4397-9679-aecf195de214">

**Comment by lingyixia** [comment]
I am also confused of why there are only "demo datasets" exists, have you already acquired a full one?

**Comment by ZiruiSongBest** [comment]
> I am also confused of why there are only "demo datasets" exists, have you already acquired a full one?

I suggest you can search the DirveGPT4(which are done by HKU). And then ask for their dataset.

**Comment by hli2020** [comment]
> I am also confused of why there are only "demo datasets" exists, have you already acquired a full one?

Still there are some quality issues as to the annotations. We want to provide a high-quality version before public release. You want to a high-quality version as well, right?

**Comment by lingyixia** [comment]
> > I am also confused of why there are only "demo datasets" exists, have you already acquired a full one?
> 
> I suggest you can search the DirveGPT4(which are done by HKU). And then ask for their dataset.

I really have asked for it several days ago and waiting for a reply, by the way, do you have the raw [BDD-X dataset](https://github.com/JinkyuKimUCB/BDD-X-dataset)？ the links to these videos seem to be invalid

**Comment by lingyixia** [comment]
> > I am also confused of why there are only "demo datasets" exists, have you already acquired a full one?
> 
> Still there are some quality issues as to the annotations. We want to provide a high-quality version before public release. You want to a high-quality version as well, right?

Of course right, looking forward to your fascinating work!

**Comment by ChonghaoSima** [comment]
> Hi, just to clarify, does it mean that this dataset only contains the demo at the moment? I noticed a table in readme saying that this DriveLM 2023 has been released (screenshot is as follow). So I get confused.
> 
> <img alt="截屏2023-09-15 22 23 41" width="862" src="https://user-images.githubusercontent.com/113589817/268309406-f805a293-1359-4397-9679-aecf195de214.png">

this is saying that we plan to release the full dataset in 2023. It's now expected to be released in November.

**Comment by ChonghaoSima** [comment]
> > > I am also confused of why there are only "demo datasets" exists, have you already acquired a full one?
> > 
> > 
> > I suggest you can search the DirveGPT4(which are done by HKU). And then ask for their dataset.
> 
> I really have asked for it several days ago and waiting for a reply, by the way, do you have the raw [BDD-X dataset](https://github.com/JinkyuKimUCB/BDD-X-dataset)？ the links to these videos seem to be invalid

FYI, we downloaded the bdd dataset from their original website (https://bdd-data.berkeley.edu/). Using the [code](https://github.com/JinkyuKimUCB/explainable-deep-driving/blob/master/Step0_download_BDDVdata.py) might not work.

**Comment by ChonghaoSima** [comment]
For the full dataset, it's now expected to be released in November.
