### ISSUE TITLE
Can you provide more information about DriveLM-CARLA? 

### ISSUE THREAD

**Issue by hutchinsonian** [OpenDriveLab/DriveLM#21]
How to get answers to the questions in the full graph of DriveLM-CARLA？

**Comment by RenzKa** [comment]
Hi,
thanks for your interest in our work.
Do you mean how we get the ground truth answers?

We collect data in CARLA with a privileged rule-based algorithm. During the data collection, we save privileged information from the simulator and information from the rule-based algorithm about the "triggered" rules for the current decision. So we have a range of metadata about perception-related things and decision-related things. 
With this metadata, we constructed a set of heuristics to create questions and answers for DriveLM-CARLA.

Let me know if this answers your question :)
Best,
Katrin

**Comment by hutchinsonian** [comment]
> Hi, thanks for your interest in our work. Do you mean how we get the ground truth answers?
> 
> We collect data in CARLA with a privileged rule-based algorithm. During the data collection, we save privileged information from the simulator and information from the rule-based algorithm about the "triggered" rules for the current decision. So we have a range of metadata about perception-related things and decision-related things. With this metadata, we constructed a set of heuristics to create questions and answers for DriveLM-CARLA.
> 
> Let me know if this answers your question :) Best, Katrin

Thank you for your reply, can you publish the code for the part "constructed a set of heuristics to create questions and answers", or can you provide more detailed information?

**Comment by RenzKa** [comment]
Hi,
we have released the full CARLA-data now. It is based on an improved version of PDM-lite which was the base for the two winning entries of the CARLA challenge 2024. We also improved the VQA labels to include VQAs for most CARLA Leaderboard 2.0 scenarios.
You can find the full driving dataset together with the VQA labels and the scripts to generate both in the branch DriveLM-CARLA.

**Comment by ayesha-ishaq** [comment]
Hi,
The drivelm carla vqas are available, but there are no train/test splits. Could you share information on this? How can I get the different train test splits?
Thank you
