### ISSUE TITLE
Recommended Experimental Settings

### ISSUE THREAD

**Issue by Sprinter1999** [OpenDriveLab/DriveLM#22]
Hi DriveLM organizers, thank you for this hard and meaningful work! I'm wondering the recommended experimental settings (e.g., V100 (32G) * 4 will be enough?) for reimplementing this baseline.

**Comment by ChonghaoSima** [comment]
We recommend v100*8 for one day fine tuning to get a somewhat decent result.

Best
Chonghao Sima
________________________________
From: Xuefen ***@***.***>
Sent: Sunday, March 3, 2024 10:10:53 PM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] Recommended Experimental Settings (Issue #22)

---- External Email: Use caution with attachments, links, or sharing data ----


Hi DriveLM organizers, thank you for this hard and meaningful work! I'm wondering the recommended experimental settings (e.g., V100 (32G) * 4 will be enough?) for reimplementing this baseline.
