### ISSUE TITLE
Get "hashes" error when run "pip install -r requirements.txt" command

### ISSUE THREAD

**Issue by brodermind** [OpenDriveLab/DriveLM#26]
When i run `pip install -r requrements.txt`, I get  the following error
`ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch==2.0.0+cu117 from https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp38-cp38-linux_x86_64.whl#sha256=c4dbc3f7f3eff6576473c3711d5d99adaaef733490b39de4970980d6edf4f0c2 (from -r requirements.txt (line 2)):
        Expected sha256 c4dbc3f7f3eff6576473c3711d5d99adaaef733490b39de4970980d6edf4f0c2
             Got        24f2904c7d84dc64995c74a9130dee6aa83486212c5a09b703e82a083ef67278
` 

I have also tried `pip cache purge`  and then run `pip install --no-cache-dir -r requirements.txt `, but get the same error. How can i fixed the peoblem ?

**Comment by ChonghaoSima** [comment]
hi, it seems like an install error of llama-adapter-v2 env. have you ask or search for the same issue in their repo?

**Comment by ChonghaoSima** [comment]
Follow-up, dose the above comment solve your concern?

**Comment by brodermind** [comment]
> Follow-up, dose the above comment solve your concern?

Hi, maybe my network issue, i have download it by chrome and it works. Thanks your answer!

**Comment by ChonghaoSima** [comment]
closing as the issue slovled
