### ISSUE TITLE
Question about the baseline model 

### ISSUE THREAD

**Issue by janghyuncho** [OpenDriveLab/DriveLM#27]
Thank you for the great work! I would like to ask a few questions about the baseline model (finetuned LLaMA Adapter V2). 

1) Is the result from a model trained on full train split of DriveLM? In this context, what does "[zero-shot result](https://github.com/OpenDriveLab/DriveLM/tree/main/challenge#results)" mean? 
2) Are you planning to release the finetuned model?  

Thank you!

**Comment by DevLinyan** [comment]
1. We offer a comprehensive procedure for a subset of DriveLM, though it is entirely acceptable if you prefer to execute it using the full training split of DriveLM. The term "zero-shot result" refers to the fact that LLaMA Adapter V2 is pre-trained on a generic dataset and has not undergone fine-tuning specifically on DriveLM.
2. We currently do not have any intentions to make the fine-tuned model publicly available. This decision is rooted in the ease with which users can perform model fine-tuning based on our provided tutorial.

**Comment by janghyuncho** [comment]
Thank you for your reply! So the baseline model is trained on some subset of DriveLM but also jointly trained on other dataset?

**Comment by DevLinyan** [comment]
The baseline model is finetuned on the subset of DriveLM only. We do not use extra data.

**Comment by janghyuncho** [comment]
Thank you!
