### ISSUE TITLE
Evaluation error on my model as it outputs  <c3,CAM_FRONT,1100.0,500.0,50.0>. (3 digit coords)

### ISSUE THREAD

**Issue by junh0cho** [OpenDriveLab/DriveLM#29]
my model output wrong instance as <c3,CAM_FRONT,1100.0,500.0,50.0>. (3 coords)

```python
import re, numpy as np 
answer="<AI answer>"

answer_nums = re.findall(r'\d+\.\d+', answer)
print(answer_nums)
answer_nums = np.array([list(map(float, x.split()))[0] for x in answer_nums]).reshape(-1, 2)
print(answer_nums)
```
above example script described in `evaluation.py`  https://github.com/OpenDriveLab/DriveLM/blob/f3a760b2d635b313ca98edb8cc2cf5e2c1184661/challenge/evaluation.py#L62-L66

seems to extract coordinates.

if answer contains correct format (2 coords per object), they are parsed well.
```
answer = "There is a white truck to the front of the ego vehicle, a white sedan to the back of the ego vehicle, and a white sedan to the front of the ego vehicle. The IDs of these objects are <c1,CAM_FRONT,1000.0,500.0>, <c2,CAM_BACK,850.0,500.0>, and <c3,CAM_FRONT,1000.0,500.0>."
>> printed
['1000.0', '500.0', '850.0', '500.0', '1000.0', '500.0']
[[1000.  500.]
 [ 850.  500.]
 [1000.  500.]]
```

but if some object has 3 coords, the code fails.
```
answer = "There is a black sedan to the back of the ego vehicle, a black sedan to the front of the ego vehicle, a black sedan to the front of the ego vehicle, and a black sedan to the front of the ego vehicle. The IDs of these objects are <c1,CAM_BACK,1000.0,500.0>, <c2,CAM_FRONT,1000.0,500.0>, and <c3,CAM_FRONT,1100.0,500.0,50.0>."
>>
Traceback (most recent call last):
  File "evaluation.py", line 134, in <module>
    evaluation.set_graph(predict, GT)
  File "evaluation.py", line 82, in set_graph
    self.graph = self.match_result(answer, GT)
  File "evaluation.py", line 68, in match_result
    answer_nums = np.array([list(map(float, x.split()))[0] for x in answer_nums]).reshape(-1, 2)
ValueError: cannot reshape array of size 7 into shape (2)
```
I would fix evaluation to only extract two digits per `< object >` rather than using regexp.

My point is, am I allowed to correct `evaluation.py` to correct model output format?
if so, generally how far am I allowed to correct AI output? 
what would be violations to the challenge rule?

**Comment by DevLinyan** [comment]
Feel free to engage in post-processing to enhance your answer, ensuring that any modifications made are aimed at improvement rather than artificial alteration.

**Comment by ChonghaoSima** [comment]
Follow-up, dose the above comment solve your concern?

**Comment by junh0cho** [comment]
yes and closing the issue
