### ISSUE TITLE
How do you build this dataset? When will you fully release the data?

### ISSUE THREAD

**Issue by ZhangGongjie** [OpenDriveLab/DriveLM#3]
Nice job! This work really sheds light on the future of autonomous driving using the power of LLMs or LMMs!

May I ask how do you build this dataset? Besides, when can we get the full dataset?

**Comment by ChonghaoSima** [comment]
1. we annotate them in two ways. one is auto-generated, the other is by manually labelled.
2. for the full dataset, it's expected to be released in November.
