### ISSUE TITLE
Question About GVQA Data 

### ISSUE THREAD

**Issue by hctian713** [OpenDriveLab/DriveLM#31]
Hi， it's great work for AD's development with LLM.
When I got `test.json` by  running `exract_data.py`, I found it was not like the GVQA structure mentioned in paper. and the training doesn't contain the Context(C) QA. So I wanna know if it's the final version about training or will be updated ?
thanks!

**Comment by ChonghaoSima** [comment]
We don’t have a plan of releasing the context for each question in this challenge as we don’t want to limit the prompting idea of the participants. However it’s rather illustrative in the paper that how we construct the gvqa by appending QA in previous stage into the behavior question.

Best
Chonghao Sima
________________________________
From: StarBurger ***@***.***>
Sent: Friday, March 8, 2024 10:51:52 AM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] Question About GVQA Data (Issue #31)

---- External Email: Use caution with attachments, links, or sharing data ----


Hi， it's great work for AD's development with LLM.
When I got test.json by running exract_data.py, I found it was not like the GVQA structure mentioned in paper. and the training doesn't contain the Context(C) QA. So I wanna know if it's the final version about training or will be updated ?
thanks!

**Comment by hctian713** [comment]
thank you for your reply

**Comment by HuangChiEn** [comment]
wow, just looking the same question, TKS for clarification~
