### ISSUE TITLE
Image in the llama sample is in the wrong fold?

### ISSUE THREAD

**Issue by milk-bottle-liyu** [OpenDriveLab/DriveLM#32]
Please check the following image. May be it should be in the fold **CAM_BACK_RIGHT**?
challenge/llama_adapter_v2_multimodal7b/data/nuscenes/samples/CAM_FRONT_RIGHT/n008-2018-09-18-13-10-39-0400__CAM_BACK_RIGHT__1537291002278113.jpg

**Comment by DevLinyan** [comment]
Thanks for pointing it out, we will fix it.
