### ISSUE TITLE
Inclusion of Important Object IDs in test/validation set

### ISSUE THREAD

**Issue by dongyang2011** [OpenDriveLab/DriveLM#35]
Hi there, will the test/validation set include important object IDs (the "key_object_infos" dict)? If not, how will questions of subsequent steps (prediction/planning, etc.) be composed with the ID?

**Comment by ChonghaoSima** [comment]
Thank you for a good question. We put some effort here to bypass the problem of id-issue.
1. The model still needs to identify the key objects.
2. If the model identifies the key objects with different id-number in the gt (the c-id in your sentence), we will use the IoU matching of the predicted and the GT 2D coordinate, to find the corrent object in your predicted answer. That being said, the c-id is not a matter here. You could have a look at our evaluation code about this.

**Comment by dongyang2011** [comment]
Thanks for the comment!
