### ISSUE TITLE
Can not install language-evaluation package

### ISSUE THREAD

**Issue by 9p15p** [OpenDriveLab/DriveLM#37]
https://github.com/OpenDriveLab/DriveLM/tree/main/challenge#setup-1

![image](https://github.com/OpenDriveLab/DriveLM/assets/40333030/d2ffff3d-30d1-4c5d-bd5c-e5e15c43c186)

This is my system_info 
![image](https://github.com/OpenDriveLab/DriveLM/assets/40333030/77b1e56e-f3ab-4ba5-8435-3b47865e765e)

Please help me, Thank you.

**Comment by ChonghaoSima** [comment]
have you try skipping the first step and then do the second step as we suggest?

**Comment by 9p15p** [comment]
Thank you,

I skip the first step & install java1.8 offline. 
It works.

**Comment by ChonghaoSima** [comment]
would be great if you could provide a pr and we merge into the document for other challenge participants
