### ISSUE TITLE
Leveraging additional information from nuscenes

### ISSUE THREAD

**Issue by dongyang2011** [OpenDriveLab/DriveLM#38]
Hi there, we're considering if the agent could benefit from more than just keyframe images to generate the right answers. Is that possible to use some extra infomations from nuscenes in this task, like continuous frame images or radar points,  which can be used to obtain more precise velocity information?

**Comment by ChonghaoSima** [comment]
you are free to do so

**Comment by ChonghaoSima** [comment]
you can also consider other modality as long as it's provided by nusc dataset

**Comment by dongyang2011** [comment]
So the full nuscenes dataset will be provided at challenge/llama_adapter_v2_multimodal7B/data/nuscene, right? And I guess the annotations, such as map expansion, lidar seg... will not be available.

**Comment by ChonghaoSima** [comment]
no, we won't provide the "full" nuscenes dataset here. you can refer to bevformer or other repo to download the full dataset.

no, those annotation (bbox, map, lidar seg) should not be used when inference.

**Comment by dongyang2011** [comment]
Do you mean that you will not provide the full nuscenes in this repo, but on the test server we can somehow access to the full nuscenes dataset (without any annotation)?

**Comment by ChonghaoSima** [comment]
not sure what do you mean by "on the test server we can somehow access to the full nuscenes dataset".

we do not restrict the input modality and history frames for the inference of the model, while we don't allow using any human-labelled annotation as well as nusc provided ground truth annotation (including but not limited to bbox, map, lidar seg).

**Comment by dongyang2011** [comment]
Thanks !

**Comment by dongyang2011** [comment]
> while we don't allow using any human-labelled annotation as well as nusc provided ground truth annotation (including but not limited to bbox, map, lidar seg).
Is it opposite of the Huggingface homepage - Specific Rules?
