### ISSUE TITLE
Some issues for ChatGPT api in evaluation.py

### ISSUE THREAD

**Issue by Sprinter1999** [OpenDriveLab/DriveLM#39]
Hi organizers, thank you for  your recent timely replies. We run into an issue when we run evaluation,py. Detailedly, in the line 27 "scores = self.chatgpt_eval.forward(answer, GT)", sometimes we will receive error from open-ai server "openai.error.ServiceUnavailableError: The server is overloaded or not ready yet". I guess this issue is mainly due to open-ai server. However, if we participants often run into this question, it will cost extra time and expense to use the open-ai api. We have tried to slow down the request rate (for example, sleep for 1 second after sending one remote service request), but similar issue still exitis. Is there any possible tips?

**Comment by ChonghaoSima** [comment]
first this is a general issue of the open-ai server that we couldn't provide a solid fix here. 

we suggest bypassing this issue by using multiple keys in parallel way so that each key will be less loaded.
