### ISSUE TITLE
is it ok to use nuScenes mini dataset？

### ISSUE THREAD

**Issue by jing-4369** [OpenDriveLab/DriveLM#4]
is it ok to use nuScenes mini dataset or it have to work with nuScenes full dataset?
Because full nuScenes data is about 500G and the downloading often crush at www.nuscenes.org/download.
i just want explore some mini set data in driveLM. 
Or can you tell me how to get nuScenes dataset quickly?

**Comment by ChonghaoSima** [comment]
maybe getting nuScenes from opendatalab https://opendatalab.com/OpenDataLab/nuScenes ?

**Comment by jing-4369** [comment]
i'll try it, thank you
