### ISSUE TITLE
How to run demo.py on multi-GPUs?

### ISSUE THREAD

**Issue by dszpr** [OpenDriveLab/DriveLM#43]
Hi, appreciate the great work!
I noticed that the demo.py used for inference is only suitable for single GPU, which make it really slow to get an output.json file. How can I run the inference on multi-GPUs? Do you have scrips for multi-GPUs inference?

**Comment by jeremyxu1998** [comment]
Hi there, thank you for your feedback! We will work on supporting multi-GPU inference, we will keep you posted

**Comment by DevLinyan** [comment]
We have supported the multi-GPU inference in the repo. Please proceed to update your code accordingly to leverage this functionality.

**Comment by dszpr** [comment]
Many thanks！Issue closed.

**Comment by alpha2003hi** [comment]
请问对gpu的需求怎么样
