### ISSUE TITLE
Inconsistent Annotations and Image Bounds

### ISSUE THREAD

**Issue by Lesliefans0-0** [OpenDriveLab/DriveLM#5]
**Description:**

It has been observed that for the `nuscenes` dataset, all camera images (whether front, back, left, or right) have a fixed resolution of (1600, 900). However, there are instances where labels in the annotations exceed these bounds.

**Examples:**

1. **Key Frame with token 1537296390262404:**
   - Annotation: "<c5,CAM_FRONT_RIGHT,2343.0,298.0>": 
   This denotes a `<moving> <car>` positioned to the `<front right>` of the ego car. 
   - Issue: The x-coordinate `2343.0` is clearly out of the 1600x900 bounds.

2. **Key Frame with token 1531883988362460:**
   - Visual representation: 
   ![image_1531883988362460_with_points](https://github.com/OpenDriveLab/DriveLM/assets/61131710/ded69d62-2912-446e-95f1-f89f58d3ed83)
   - Annotations: 
     - 1486.5, 320.5
     - 1544.0, 304.0
     - 1317.5, 310.0
   - Issue: Despite these coordinates suggesting that the objects should be located at the right-top corner of the image, the visual representation shows them in the center. Although their relative positions appear correct, there seems to be a mismatch in the coordinate system.

**Concern:**
There might be a misalignment or inconsistency in how the coordinates are being represented and annotated.

**Comment by ChengenXie** [comment]
Hi, in our currently published dataset, the labeled coordinates are the global coordinates after stitching the six images together (the whole picture size is 2880*1040). You can read the [docs/getting_started.md](url) for more details.
On the other hand, we also realised that such an annotation would pose an obstacle when training the model, so in the latest version of the dataset, we adjusted the coordinates of the annotations all the way down to the coordinates in a single image.

**Comment by Lesliefans0-0** [comment]
Thank you for telling me that! There is still a problem, if we concatenate 6 pictures by 2*3 and if each is 1600*900, we got 4800*1800; I can assume that you made some resizing, but 4800:1800=8:3, while 2800:1040 is about 8.07:3. Nearly but different. Do you mean 2800:1080?

**Comment by ChonghaoSima** [comment]
> Thank you for telling me that! There is still a problem, if we concatenate 6 pictures by 2*3 and if each is 1600*900, we got 4800*1800; I can assume that you made some resizing, but 4800:1800=8:3, while 2800:1040 is about 8.07:3. Nearly but different. Do you mean 2880:1080?

We will revive this problem in the next release. The (x,y) will be the per-image coordinates, with a CAM_XXX tag to specify which camera is that object in.
