### ISSUE TITLE
The meaning of C_loss and M_loss

### ISSUE THREAD

**Issue by 9p15p** [OpenDriveLab/DriveLM#51]
https://github.com/OpenDriveLab/DriveLM/blob/2f4ccfe6327a39f1727aa507249623f2bf9d0ce0/challenge/llama_adapter_v2_multimodal7b/engine_finetune.py#L39

It seems that C_loss and M_loss are the same variable. 
what exactly do C_loss and M_loss mean? and why do we distinguish between them?

Thank you.

**Comment by ChonghaoSima** [comment]
Closing as no further response.
