### ISSUE TITLE
Got wrong reply from ChatGPT

### ISSUE THREAD

**Issue by piqiuni** [OpenDriveLab/DriveLM#53]
With the [output.json](https://github.com/OpenDriveLab/DriveLM/blob/main/challenge/output.json) and [test_eval.json](https://github.com/OpenDriveLab/DriveLM/blob/main/challenge/test_eval.json) in this repo, we got the wrong reply from ChatGPT

> [{'role': 'system', 'content': 'an evaluator who rates my answer based on the correct answer'}, {'role': 'user', 'content': 'Rate my answer based on the correct answer out of 100, with higher scores indicating that the answer is closer to the correct answer, and you should be accurate to single digits like 62, 78, 41,etc. Output the number only

> This is the correct answer: Firstly, notice <c3,CAM_FRONT_LEFT,1075.5,382.8>. The object is a traffic sign, so the ego vehicle should continue at the same speed. Secondly, notice <c2,CAM_FRONT,836.3,398.3>. The object is a traffic sign, so the ego vehicle should accelerate and continue ahead. Thirdly, notice <c1,CAM_BACK,991.7,603.0>. The object is stationary, so the ego vehicle should continue ahead at the same speed.

> This is my answer: 1. The ego vehicle should notice the traffic light first, as it is the first object in the image. The traffic light is in the process of changing from red to green, indicating that the vehicle should proceed with caution.2. The ego vehicle should notice the truck next, as it is the second object in the image. The truck is stopped at the intersection, and the ego vehicle should be cautious when approaching the intersection to ensure it does not collide with the truck.3. The ego vehicle should notice the bus next, as it is the third object in the image. The bus is stopped at the intersection, and the ego vehicle should be cautious when approaching the intersection to ensure it does not collide with the bus.4. The ego vehicle should notice the traffic light next, as it is the fourth object in the image. The traffic light is in the process of changing from green to red, indicating that the vehicle should stop at the intersection.5. The ego vehicle should notice the truck next, as it is the fifth object in the image. The truck is stopped at the intersection, and the ego vehicle should be cautious when approaching the intersection to ensure it'}]

> Sorry, but I cannot evaluate your answer based on the correct answer as the two responses are completely different.

Please help to figure this problem.
Should we add a "is completely different, give a '0' reply" in the content?

**Comment by DevLinyan** [comment]
Could you provide your code in the `gpt_eval.py`?

**Comment by DevLinyan** [comment]
Try it again? We have updated the version.

**Comment by piqiuni** [comment]
@DevLinyan 
The new code shown blow can't work, because the "openai.ChatCompletion, but this is no longer supported in openai>=1.0.0". 
> response = openai.ChatCompletion.create(
            model=model, messages=chatgpt_messages, temperature=0.6, max_tokens=max_tokens
        )
        reply = response["choices"][0]["message"]["content"]
        total_tokens = response["usage"]["total_tokens"]

With the old version blow, I can assess ChatGPT but still receive "ValueError: could not convert string to float: "I'm sorry, but your answer does not match the correct answer provided. Therefore, I cannot provide a rating for your answer.""
 > response = openai.chat.completions.create(
            model=model, messages=chatgpt_messages, temperature=0.6, max_tokens=max_tokens
        )
        reply = response.choices[0].message.content
        total_tokens = response.usage.total_tokens

**Comment by DevLinyan** [comment]
Could you provide additional details? I'm unable to replicate the `error` you mentioned.

**Comment by piqiuni** [comment]
[tt.json](https://github.com/OpenDriveLab/DriveLM/files/14731057/tt.json)
[tt2.json](https://github.com/OpenDriveLab/DriveLM/files/14731058/tt2.json)
Run ``python evaluation.py --root_path1 ./tt2.json --root_path2 ./tt.json`` lead to "ValueError: could not convert string to float: "I'm sorry, but your answer does not match the correct answer provided. Therefore, I cannot provide a rating for your answer.""


In the "gpt_eval.py", I change the openai.api_key and openai.base_url="https://api.chatanywhere.tech"
I think the openai.base_url won't influence the answer?
