### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by LuPaoPao** [OpenDriveLab/DriveLM#6]
Thank you very much for your team's outstanding contribution to the field. However, I tried to fill in the Google form three times to apply for all LM annotations, but I didn't get any reply, and I could only get demo annotations. Can you help me? Thanks again.

**Comment by ChonghaoSima** [comment]
We are preparing for the full-scale dataset release. Sorry for the delay.

**Comment by ChonghaoSima** [comment]
It's [released](https://github.com/OpenDriveLab/DriveLM/blob/main/docs/data_prep_nus.md) now.

**Comment by LuPaoPao** [comment]
> It's [released](https://github.com/OpenDriveLab/DriveLM/blob/main/docs/data_prep_nus.md) now.

Thank you for your response and thank you again for your outstanding contributions.
