### ISSUE TITLE
Which split should be submitted to the test server

### ISSUE THREAD

**Issue by NaNaoiSong** [OpenDriveLab/DriveLM#61]
Thanks for the great work for AD LLM. The test server has opened, but it seems there is no new test split provided. So which split is used for test server, is `test_llama.json`?

**Comment by ChonghaoSima** [comment]
We haven't release the test split yet. Please stay tuned for the official annoucement in this repo.

**Comment by ChonghaoSima** [comment]
Yes.

**Comment by NaNaoiSong** [comment]
I see and thx again!
