### ISSUE TITLE
Got error when running the code "sudo add-apt-repository ppa:webupd8team/java" during the evaluation stage.

### ISSUE THREAD

**Issue by yabuke** [OpenDriveLab/DriveLM#65]
Got error when running the code "sudo add-apt-repository ppa:webupd8team/java" during the evaluation stage.
![1711476587416](https://github.com/OpenDriveLab/DriveLM/assets/122121799/b9e263e7-9a78-41ee-a94d-bbe541f8c8bd)

**Comment by ChonghaoSima** [comment]
not sure if this could help but please take a look and discuss with them https://github.com/OpenDriveLab/DriveLM/issues/37

**Comment by jeremyxu1998** [comment]
Can you also try to change the apt source? https://github.com/bckim92/language-evaluation/issues/3

**Comment by yabuke** [comment]
> Can you also try to change the apt source? [bckim92/language-evaluation#3](https://github.com/bckim92/language-evaluation/issues/3)

I have tried, but got same error.
