### ISSUE TITLE
finetuning resource needed for challenge

### ISSUE THREAD

**Issue by AHPUymhd** [OpenDriveLab/DriveLM#66]
Hello, I checked your contest docs, it shows that the RAM required for reasoning and fine-tuning is 34/35Gb, but I don't have that high graphics card, can I reduce the batch_size to reduce the amount of video memory required?

**Comment by AHPUymhd** [comment]
By the way, I only have a 4090, can I participate in the challenage？

**Comment by ChonghaoSima** [comment]
It should be possible to use one 4090 if you reduce the batch_size.

**Comment by ChonghaoSima** [comment]
Closing as no further response.
