### ISSUE TITLE
Can the baseline model be replaced?

### ISSUE THREAD

**Issue by yabuke** [OpenDriveLab/DriveLM#68]
In this competition, we can replace the llama_adapter_v2 with other version llama_adapter or other LLM? I have same question in the visual encoder. Or do we just need to consider how to use fine-tuning techniques and other tricks to improve the performance of the model? 
This may be a very basic question, sorry, it's my first time participating in this kind of competition.

**Comment by ChonghaoSima** [comment]
sure, you can use whatever model you like. the baseline model is just a starting pointer for the begineer.

**Comment by ChonghaoSima** [comment]
Closing as no further response.
