### ISSUE TITLE
Inference OutOfMemoryError with the same params of Finetune. 

### ISSUE THREAD

**Issue by piqiuni** [OpenDriveLab/DriveLM#69]
I got the `torch.cuda.OutOfMemoryError` in demo.py. But the params of `--batch_size` and  `--num_processes` are the same with Finetune. (--batch_size 1 --num_processes 2 with 4090*2)

Is that caused by the total Vmemory usage (weights 13GB + checkpoint-3.pth 14GB + else) over the 24GB of 4090?
How can I run the Inference using the VRAM of two GPUs? 
Or should we quantize the model to reduce the VRAM usage to run on a single 4090?

Can you give us advice on dealing with the problem?
Thanks a lot!

**Comment by ChonghaoSima** [comment]
it could be the problem of max_length, you could check if you fully utilize the max_length during training will oom?

**Comment by piqiuni** [comment]
@ChonghaoSima  
Sorry, I didn’t find the max_length param in the code.

**Comment by piqiuni** [comment]
And with the official pre-trained checkpoint(400MB), we can't run the Inference baseline, we have no idea of the error. 
Please help!

**Comment by piqiuni** [comment]
With the old code of March 22, with demo.py using Process instead of Thread, the Inference baseline is runable with official pre-trained checkpoint(400MB).
Can you help check up the code?

**Comment by DevLinyan** [comment]
You can use any other smaller model as your baseline, such as `BLIP2`.

**Comment by piqiuni** [comment]
Close with bug report in #73
