### ISSUE TITLE
got error when i want to pretrian the model

### ISSUE THREAD

**Issue by yabuke** [OpenDriveLab/DriveLM#72]
The PretrainDataset class in dataset.py is right? it cannot used for load data from test_llama.json. I read the code, then found the data form of  PretrainDataset class needed and FinetuneDataset is different.

**Comment by DevLinyan** [comment]
Yes, the code provided is specifically for fine-tuning. If you intend to perform pretraining, you should refer to the instructions provided in the [llama_adapter](https://github.com/OpenGVLab/LLaMA-Adapter) repository.

**Comment by ChonghaoSima** [comment]
Closing as no further response.
