### ISSUE TITLE
Bug Report: max_batch_size set to 32 in llama_adapter.load lead to OutOfMemoryError in Inference Baseline

### ISSUE THREAD

**Issue by piqiuni** [OpenDriveLab/DriveLM#73]
Related to #69.
Line 316 in llama_adapter.py, set the default value to 32 lead to OutOfMemoryError in Inference Baseline.

**Comment by piqiuni** [comment]
With RTX 4090 24GB, the max_batch_size can be set to 16 or 8

**Comment by DevLinyan** [comment]
You can reduce the batch size until it fits within your available memory capacity.

**Comment by tenderzada** [comment]
> With RTX 4090 24GB, the max_batch_size can be set to 16 or 8

I'm using the same setup and I'm having the GPU out of memory problem when inferring. May I ask if you have solved it.

**Comment by piqiuni** [comment]
@tenderzada 
Yes, just turn down the max_batch_size in llama_adapter.load, you can try to set it as 1 first.

**Comment by tenderzada** [comment]
> @tenderzada Yes, just turn down the max_batch_size in llama_adapter.load, you can try to set it as 1 first.

I did it, thank you very mach.

**Comment by tenderzada** [comment]
> @tenderzada Yes, just turn down the max_batch_size in llama_adapter.load, you can try to set it as 1 first.

I did it, thank you very much.

**Comment by yuxr-smile** [comment]
> > 是的，只需调低 llama_adapter.load 中的 max_batch_size，您可以先尝试将其设置为 1。
> 
> 我做到了，非常感谢。

I would like to know how long it took for you to run inference with max_batch_size=1.

**Comment by tenderzada** [comment]
> > > 是的，只需调低 llama_adapter.load 中的 max_batch_size，您可以先尝试将其设置为 1。
> > 
> > 
> > 我做到了，非常感谢。
> 
> I would like to know how long it took for you to run inference with max_batch_size=1.

I'm not quite sure, but I remember that it takes less than half an hour to complete one epoch.

**Comment by yuxr-smile** [comment]
Thank you very mush ！I would like to know which one I should choose for inference.
[cid:bb41f4bf-d616-49f8-b8d1-4158b3fbbfd3]

________________________________

**Comment by yuxr-smile** [comment]
The results I obtained are significantly different from the ones provided by the author.I did not use GPT for scoring.
[cid:eecc4be2-8f92-4a43-9fc9-37b72891e5c1]

________________________________

**Comment by yuxr-smile** [comment]
> > > > 是的，只需调低 llama_adapter.load 中的 max_batch_size，您可以先尝试将其设置为 1。
> > > 
> > > 
> > > 我做到了，非常感谢。
> > 
> > 
> > 我想知道您使用 max_batch_size=1 运行推理需要多长时间。
> 
> 我不太确定，但我记得完成一个 epoch 只需要不到半小时。

Thank you very mush ！I would like to know which one I should choose for inference.
![image1](https://github.com/user-attachments/assets/5bb5d8ef-daba-4ed6-aa4c-5c57506e220f)
The results I obtained are significantly different from the ones provided by the author.I did not use GPT for scoring.
` python evaluation.py --root_path1 ./output_caption.json --root_path2 ./test_eval.json`
![image](https://github.com/user-attachments/assets/a195f574-283c-479e-b610-9f7f68b4c48a)
