### ISSUE TITLE
Wrong format of DriveLM-nuScenes version-1.1 val

### ISSUE THREAD

**Issue by piqiuni** [OpenDriveLab/DriveLM#75]
During the Inference, the `DriveLM-nuScenes version-1.1 val` should have the same format as `test_llama.json`. 
But it seems the `DriveLM-nuScenes version-1.1 val` and `test_eval.json` have the same format.

So the model infer of mine on the DriveLM-nuScenes version-1.1 val led to a wrong format error.

![image](https://github.com/OpenDriveLab/DriveLM/assets/87999547/daeb26e2-ef91-40a3-963b-b1ef37e8e434)

**Comment by DevLinyan** [comment]
First, execute the [convert2llama.py](https://github.com/OpenDriveLab/DriveLM/blob/main/challenge/convert2llama.py) script to convert the format of the validation data. Subsequently, utilize the generated output for conducting inference.

**Comment by piqiuni** [comment]
Thanks for the reply!
