### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by hutslib** [OpenDriveLab/DriveLM#78]
Hi! For the challenge, when we do evaluation using the example output.json and tesdt_eval.json, the chatgpt evaluate part encounter an error 
`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/root/anaconda3/envs/llama_adapter_v2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/llama_adapter_v2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/llama_adapter_v2/lib/python3.8/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/root/anaconda3/envs/llama_adapter_v2/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() takes 1 positional argument but 2 were given
`
Could you help us solve this problem?

**Comment by hutslib** [comment]
I have try method in #62, but none is functional.

**Comment by DevLinyan** [comment]
Could you provide the linux command you use to conduct evaluation?

**Comment by hutslib** [comment]
`python evaluation.py --root_path1 ./output.json --root_path2 ./test_eval.json`

**Comment by hutslib** [comment]
I'm currently at 
`commit 48614d465f3ffc05ff5d23364343198733e1d197 `

**Comment by hutslib** [comment]
I'm currently at `5e283da0afe873876b6c50fc813a2794d579a14d`

**Comment by hutslib** [comment]
For those who meet the same issues.
Check the openai version in your environment. I guess 0.28.1 and older is ok.
For 1.X. openai has a new calling API and your need to modify could in gpt_eval.py part accordingly.
@DevLinyan Could you please give us the openai version you used in the test server?

**Comment by ChonghaoSima** [comment]
@hutslib We use the newer version of openai api as to accelerate the evaluation. In order to get a stable evaluation on your environment you could downgrade to certain version.

We also notice the instability of gpt eval as the gpt3.5 turbo sometimes gives random evaluation score. We're working on to alleviate this issue.
