### ISSUE TITLE
submission error

### ISSUE THREAD

**Issue by fcjian** [OpenDriveLab/DriveLM#79]
When I submit a Hugging Face model (submission file) to [driving-with-language-2024](https://huggingface.co/spaces/AGC2024/driving-with-language-2024), an error with the message "Invalid token" is returned.

**Comment by hctian713** [comment]
hi ！ I wanna know how you fix it？

**Comment by eiokobe** [comment]
How did you resolve this issue?

**Comment by hctian713** [comment]
just logging in huggingface



---Original---
From: ***@***.***&gt;
Date: Mon, May 20, 2024 10:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenDriveLab/DriveLM] submission error (Issue #79)




 
How did you resolve this issue?
