### ISSUE TITLE
The specific value of the metric？

### ISSUE THREAD

**Issue by yabuke** [OpenDriveLab/DriveLM#81]
The value of 2.463 for the CIREr metric in Table 10 of the paper, is it converted? Is it 2.463 or 0.02463?

**Comment by ChonghaoSima** [comment]
it's converted to 0-100 (the range of value).

**Comment by yabuke** [comment]
so, the 2.463 in paper is corresponding to 0.02463 calculated by the evaluation.py?

**Comment by ChonghaoSima** [comment]
Yes, in the evaluation.py we don't convert the range of the value
________________________________
发件人: yabuke ***@***.***>
发送时间: 2024年4月23日 16:10
收件人: OpenDriveLab/DriveLM ***@***.***>
抄送: Sima, Chonghao ***@***.***>; Comment ***@***.***>
主题: Re: [OpenDriveLab/DriveLM] The specific value of the metric？ (Issue #81)

---- External Email: Use caution with attachments, links, or sharing data ----


so, the 2.463 in paper is corresponding to 0.02463 calculated by the evaluation.py?

―

**Comment by yabuke** [comment]
I tested the evaluation.py using only one sample with correct answer, and got the value of CIDEr is 0.0.
I don't know much about this metric. Is this no problem?

**Comment by yabuke** [comment]
![1713859999798](https://github.com/OpenDriveLab/DriveLM/assets/122121799/2666be6f-8b44-41e8-b920-8d9305bb66c2)
![1713860048728](https://github.com/OpenDriveLab/DriveLM/assets/122121799/b9114947-d47d-4f6b-8b9b-015e031ea93d)
![1713860086390](https://github.com/OpenDriveLab/DriveLM/assets/122121799/2e01c312-84af-4853-a2bd-e493fdea3ecb)

**Comment by yuxr-smile** [comment]
> ![1713859999798](https://private-user-images.githubusercontent.com/122121799/324750477-2666be6f-8b44-41e8-b920-8d9305bb66c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTI1NzYsIm5iZiI6MTczMzQ1MjI3NiwicGF0aCI6Ii8xMjIxMjE3OTkvMzI0NzUwNDc3LTI2NjZiZTZmLThiNDQtNDFlOC1iOTIwLThkOTMwNWJiNjZjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwMjMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzRlZjZjZDRkNTZmODUwOTA4NzIxNDEzOTNlNDdhNTM5YzU2NWI5ZGIwOTI3N2M3YzA3OTI2NWMxNWE4MDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jjqVmMfbtxNsh-Zo8DZ3gmivsaaq_OU20q2dx0knUyA) ![1713860048728](https://private-user-images.githubusercontent.com/122121799/324750740-b9114947-d47d-4f6b-8b9b-015e031ea93d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTI1NzYsIm5iZiI6MTczMzQ1MjI3NiwicGF0aCI6Ii8xMjIxMjE3OTkvMzI0NzUwNzQwLWI5MTE0OTQ3LWQ0N2QtNGY2Yi04YjliLTAxNWUwMzFlYTkzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwMjMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzE0NGMwZDE5Mzg0OTVkZmQ5MWY3YmIyMGJkZmU5Y2MyMGIxZDdjODVlNTgwMGIxNjA5MjgwNTJkYmZlZGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r56wLktEqqyPNYAG6qAOudvMIUB_J3fUdX0y0J-ALRk) ![1713860086390](https://private-user-images.githubusercontent.com/122121799/324750990-2e01c312-84af-4853-a2bd-e493fdea3ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTI1NzYsIm5iZiI6MTczMzQ1MjI3NiwicGF0aCI6Ii8xMjIxMjE3OTkvMzI0NzUwOTkwLTJlMDFjMzEyLTg0YWYtNDg1My1hMmJkLWU0OTNmZGVhM2VjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwMjMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjNiODc1OTQ2YTJiZjdjYjUwNzMxNTNmMzM2M2NkNjI4MDdmOTRmOTEyMWVmYWViNmVmODI0M2IxMzRhZjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yv7NaH16_ObBAZXEDJECWsOQnDTA2bRRX2_N8CxsWz4)

Did you solve the problem？I met the same problem.
