### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by ffxzh** [OpenDriveLab/DriveLM#82]
It really confusing me that:
what‘s the difference between the datasets you mentioned in the results of baseline?

1. The zero-shot results of baseline on the sampled data
2. The zero-shot results of baseline on the test data
3. the dataset provided on the test server (DriveLM-nuScenes version-1.1 val)

Could you give detailed information between these datasets? 

Thanks!

**Comment by ChonghaoSima** [comment]
It's illustrative in [our description for each result](https://github.com/OpenDriveLab/DriveLM/tree/main/challenge#results)

**Comment by ffxzh** [comment]
Thanks
