### ISSUE TITLE
The release time of DriveLM-CARLA

### ISSUE THREAD

**Issue by yixiao1** [OpenDriveLab/DriveLM#83]
Hi,

Very appreciate this impressive work. 
I was wondering when will the DriveLM-CARLA dataset be released? It would be grateful to know the timeline. 
Many Thanks.

Bests,
Yi

**Comment by ChonghaoSima** [comment]
Will keep you posted [here](https://github.com/OpenDriveLab/DriveLM/issues/21)

**Comment by RenzKa** [comment]
Hi thanks for your interest in DriveLM-CARLA.
We made some major improvements to the CARLA dataset and we are working on the code clean up right now..we hope to be able to release to code to generate the data and the extracted dataset in the following weeks.

**Comment by reachpranjal** [comment]
Couldn't find the CARLA data. Has it been released?

**Comment by RenzKa** [comment]
Hi,
we have released the full CARLA-data now. It is based on an improved version of PDM-lite which was the base for the two winning entries of the CARLA challenge 2024. We also improved the VQA labels to include VQAs for most CARLA Leaderboard 2.0 scenarios.
You can find the full driving dataset together with the VQA labels and the scripts to generate both in the branch DriveLM-CARLA.
