### ISSUE TITLE
Submission Status

### ISSUE THREAD

**Issue by 2016110071** [OpenDriveLab/DriveLM#86]
Could you please tell me why my submission status is always QUEUED?

**Comment by ChonghaoSima** [comment]
Seems like hf server is undergoing some maintainance, please choose a different time to submit

**Comment by 2016110071** [comment]
Thanks. It has successed when I choose a different time to submit. But when I submit again, it shows "SyntaxError: Unexpected token I in JSON at position 0" . Could you please tell me what I should do?

**Comment by ChonghaoSima** [comment]
We recommend trying to evaluate your submission file on your machines before submitting. We provide the corresponding evaluation code for this purpose.

Best
Chonghao Sima
________________________________
