### ISSUE TITLE
why the score is different?

### ISSUE THREAD

**Issue by yabuke** [OpenDriveLab/DriveLM#88]
we test the baseline on the test server, and found the score is different with the score in paper. 
the score in paper:
![1714113708988](https://github.com/OpenDriveLab/DriveLM/assets/122121799/e5283961-5a85-4b63-9b33-cc27d3913256)
we test in test server:
{"accuracy": 0.6563218390804598, "chatgpt": 52.304035874439464, "language/Bleu_1": 0.7290411998613902, "language/Bleu_2": 0.6639121354657584, "language/Bleu_3": 0.6015739286561763, "language/Bleu_4": 0.540482940279753, "language/ROUGE_L": 0.7144301423026727, "language/CIDEr": 0.10061532435610071, "match": 33.8955710955711, "final_score": 0.4988212685585955}

**Comment by ChonghaoSima** [comment]
They are different models. Please check the detail.
