### ISSUE TITLE
Submission Failed

### ISSUE THREAD

**Issue by 1uciusy** [OpenDriveLab/DriveLM#91]
I've got a failed submission, and there is not error messages. The submission ID is 043e632e-bbd5-42ef-a9fb-4d41a21665ea, could you check out for me or tell me the traceback message? I've use the v1_1_val_nus_q_only.json as a pseudo gt file to run evaluate.py, the script works fine in my local evaluation.

**Comment by ChonghaoSima** [comment]
If there are no error messages, it may be hf server issues. Please choose another time to submit.

Best
Chonghao Sima
________________________________
From: 1uciusy ***@***.***>
Sent: Sunday, April 28, 2024 2:47:12 PM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] Submission Failed (Issue #91)

---- External Email: Use caution with attachments, links, or sharing data ----


I've got a failed submission, and there is not error messages. The submission ID is 043e632e-bbd5-42ef-a9fb-4d41a21665ea, could you check out for me or tell me the traceback message? I've use the v1_1_val_nus_q_only.json as a pseudo gt file to run evaluate.py, the script works fine in my local evaluation.
