### ISSUE TITLE
Error when convert gpt evaluation result to float type.

### ISSUE THREAD

**Issue by 1uciusy** [OpenDriveLab/DriveLM#92]
I've encountered error information as follows.

`[ERROR] Evaluation failed. could not convert string to float: 'Score: 30'`

And I've checked there is nothing like `Score:30` in my submission, I doublt this is from the evaluation from GPT, in `evaluation.py`, line 37-40, directly apply `float` function to the output of gpt eval could cause such error.

```python
        with Pool(32) as p:  # Change the number based on your CPU cores
            scores = p.map(self.chatgpt_eval.forward, data)

        scores = list(map(float, scores))
```

Could you check and fix this? The submission ID is `5994575b-5e0c-41ba-8f16-8ebf6f32d276`.

**Comment by fcjian** [comment]
I encountered the same issue.

**Comment by ChonghaoSima** [comment]
Please resubmitted recently as we update the prompts in evaluation.

Best
Chonghao Sima
________________________________
