### ISSUE TITLE
Motion trajectory prediction

### ISSUE THREAD

**Issue by mismayil** [OpenDriveLab/DriveLM#93]
I wanted to ask about the motion trajectory prediction stage. It seems like we don't have access to any training dataset for this task. Isn't this also the part of the evaluation?

**Comment by ChonghaoSima** [comment]
It’s not included in this challenge. And it’s just nuscenes ego-vehicle future trajectory.

Best
Chonghao Sima
________________________________
From: Mete Ismayilzada ***@***.***>
Sent: Tuesday, April 30, 2024 12:51:13 AM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] Motion trajectory prediction (Issue #93)

---- External Email: Use caution with attachments, links, or sharing data ----


I wanted to ask about the motion trajectory prediction stage. It seems like we don't have access to any training dataset for this task. Isn't this also the part of the evaluation?

**Comment by mismayil** [comment]
Thanks. But could you possibly share the data with us? We also wanted to evaluate our model on that.

**Comment by ChonghaoSima** [comment]
We refer to UniAD repo to prepare the data.

Best
Chonghao Sima
________________________________
