### ISSUE TITLE
Submission Status

### ISSUE THREAD

**Issue by HANSHENG-LIANG** [OpenDriveLab/DriveLM#94]
Could you please tell me why my submission status is always PROCESSING? I've been waiting for about 12 hours. How long does it usually take to validate one?

**Comment by ChonghaoSima** [comment]
Please provide your submission ID and we shall take a look.

Best
Chonghao Sima
________________________________
From: HANSHENG-LIANG ***@***.***>
Sent: Tuesday, April 30, 2024 9:48:45 AM
To: OpenDriveLab/DriveLM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenDriveLab/DriveLM] Submission Status (Issue #94)

---- External Email: Use caution with attachments, links, or sharing data ----


Could you please tell me why my submission status is always PROCESSING? I've been waiting for about 12 hours. How long does it usually take to validate one?

**Comment by HANSHENG-LIANG** [comment]
Thanks for the quick reply.
my submission ID is 28c7dd3c-3176-49d9-9e50-6957099f8f26
