### ISSUE TITLE
Public leaderboard

### ISSUE THREAD

**Issue by Zbozhou** [OpenDriveLab/DriveLM#96]
When will the public leaderboard open? Thank you.

**Comment by ChonghaoSima** [comment]
![image](https://github.com/OpenDriveLab/DriveLM/assets/54334254/b114bbaa-6f59-4bea-b92a-1d9ccd046ae7)

**Comment by ChonghaoSima** [comment]
@Zbozhou Leaderboard reopened: https://huggingface.co/spaces/AGC2024/driving-with-language-official
